#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BuiltinTypeTag {
    Unit,
    Bool,
    I8,
    I16,
    I32,
    I64,
    I128,
    Isize,
    U8,
    U16,
    U32,
    U64,
    U128,
    Usize,
    F32,
    F64,
    Char,
    String,
    Bytes,
    Array,
    List,
    Map,
    Record,
    Set,
    Range,
    Slice,
    Option,
    Result,
    Variant,
}

impl BuiltinTypeTag {
    pub fn source_name(self) -> &'static str {
        match self {
            Self::Unit => "unit",
            Self::Bool => "bool",
            Self::I8 => "i8",
            Self::I16 => "i16",
            Self::I32 => "i32",
            Self::I64 => "i64",
            Self::I128 => "i128",
            Self::Isize => "isize",
            Self::U8 => "u8",
            Self::U16 => "u16",
            Self::U32 => "u32",
            Self::U64 => "u64",
            Self::U128 => "u128",
            Self::Usize => "usize",
            Self::F32 => "f32",
            Self::F64 => "f64",
            Self::Char => "char",
            Self::String => "string",
            Self::Bytes => "bytes",
            Self::Array => "Array",
            Self::List => "List",
            Self::Map => "Map",
            Self::Record => "Record",
            Self::Set => "Set",
            Self::Range => "Range",
            Self::Slice => "Slice",
            Self::Option => "Option",
            Self::Result => "Result",
            Self::Variant => "Variant",
        }
    }
}
